### ISSUE TITLE
Add DOI for avn code?

### ISSUE THREAD

**Issue by NickleDave** [theresekoch/avn#13]
Hi (again) @theresekoch :slightly_smiling_face: 

Is there a DOI for avn?
Like, if I want to be able to cite the code directly?

If not, would you consider adding one?
E.g., by turning on [GitHub-Zenodo integration](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)?

DOIs and citing code is less than perfect, but it's better than nothing (but I'll save [that rant](https://dl.acm.org/doi/abs/10.1145/3500868.3559398) for another github issue).
Just want to make sure you get the credit you deserve

Thank you

**Comment by theresekoch** [comment]
Hi (again) :slightly_smiling_face: Thanks for the suggestion! I just added a DOI to the readme for the most recent version. Hopefully there will be a pre-print to cite too in a month or so :crossed_fingers:

**Comment by NickleDave** [comment]
Excellent, thank you! Looking forward to reading the pre-print! :raised_hands:
